### ISSUE TITLE
Turn on discussions

### ISSUE THREAD

**Issue by Explosion-Scratch** [asmcss/assembler#9]
It would be really nice to be able to use [GitHub Discussions](https://docs.github.com/en/discussions), to turn them on go into the [repository settings](https://github.com/asmcss/assembler/settings) and find the discussions section:
![image](https://user-images.githubusercontent.com/61319150/131684668-6ec5e49e-7233-47c9-9ddd-ebb3d6ab0729.png)

**Comment by msarca** [comment]
Done

**Comment by Explosion-Scratch** [comment]
Thanks! =)
